before_script:
  - psql -c 'create database notes_test;' -U postgres

language: python
python:
  - "2.7"

env:
  - DATABASE_URL = "postgres://postgres:@127.0.0.1/notes_test"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests