#!/bin/sh

#form: postgres://user:password@host:port/database
export DATABASE_URL=postgres://xorrr:@localhost/test

# -x <- stop running tests after the first error or failure
nosetests --rednose -s -x
